/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as ProtectedInstructorRouteImport } from './routes/_protected/_instructor'
import { Route as ProtectedCoursesCourseIdRouteImport } from './routes/_protected/courses.$courseId'
import { Route as ProtectedInstructorCoursesNewRouteImport } from './routes/_protected/_instructor/courses.new'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedInstructorRoute = ProtectedInstructorRouteImport.update({
  id: '/_instructor',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoursesCourseIdRoute =
  ProtectedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInstructorCoursesNewRoute =
  ProtectedInstructorCoursesNewRouteImport.update({
    id: '/courses/new',
    path: '/courses/new',
    getParentRoute: () => ProtectedInstructorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/signup': typeof PublicSignupRoute
  '/': typeof ProtectedIndexRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdRoute
  '/courses/new': typeof ProtectedInstructorCoursesNewRoute
}
export interface FileRoutesByTo {
  '/signup': typeof PublicSignupRoute
  '/': typeof ProtectedIndexRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdRoute
  '/courses/new': typeof ProtectedInstructorCoursesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/_instructor': typeof ProtectedInstructorRouteWithChildren
  '/_public/signup': typeof PublicSignupRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/courses/$courseId': typeof ProtectedCoursesCourseIdRoute
  '/_protected/_instructor/courses/new': typeof ProtectedInstructorCoursesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/signup' | '/' | '/courses/$courseId' | '/courses/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/signup' | '/' | '/courses/$courseId' | '/courses/new'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/_instructor'
    | '/_public/signup'
    | '/_protected/'
    | '/_protected/courses/$courseId'
    | '/_protected/_instructor/courses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/_instructor': {
      id: '/_protected/_instructor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedInstructorRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$courseId': {
      id: '/_protected/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof ProtectedCoursesCourseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_instructor/courses/new': {
      id: '/_protected/_instructor/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof ProtectedInstructorCoursesNewRouteImport
      parentRoute: typeof ProtectedInstructorRoute
    }
  }
}

interface ProtectedInstructorRouteChildren {
  ProtectedInstructorCoursesNewRoute: typeof ProtectedInstructorCoursesNewRoute
}

const ProtectedInstructorRouteChildren: ProtectedInstructorRouteChildren = {
  ProtectedInstructorCoursesNewRoute: ProtectedInstructorCoursesNewRoute,
}

const ProtectedInstructorRouteWithChildren =
  ProtectedInstructorRoute._addFileChildren(ProtectedInstructorRouteChildren)

interface ProtectedRouteChildren {
  ProtectedInstructorRoute: typeof ProtectedInstructorRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedCoursesCourseIdRoute: typeof ProtectedCoursesCourseIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedInstructorRoute: ProtectedInstructorRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedCoursesCourseIdRoute: ProtectedCoursesCourseIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
